name = "tickets-images-worker"
main = "src/index.tsx"
compatibility_date = "2022-12-01"
node_compat = true
kv_namespaces = [
    { binding = "TICKETS_QR_IMAGES", id = "aa45c255f6f441dda71e45b0c11f132a" , preview_id = "b297786957b249dca99978fad2cf95cb" }
]

[vars]
API_URL = "http://127.0.0.1:8080/api/v1/tickets/qr/info"
APP_ENV =  "localhost"
TTL_EN_SEGUNDOS = 60

[env.dev]
name = "tickets-images-worker-dev"

[env.dev.vars]
API_URL = "https://tickets-api-dev.fly.dev/api/v1/tickets/qr/info"
APP_ENV =  "dev"
TTL_EN_SEGUNDOS = 60

[env.production]
name = "tickets-images-worker-production"

[env.production.vars]
API_URL = "https://tickets-api-production.fly.dev/api/v1/tickets/qr/info"
APP_ENV = "production"
TTL_EN_SEGUNDOS = 600
# TTL_EN_SEGUNDOS = 2678400
